name: Test

on:
  pull_request:
  push:
    branches: [ main ]

env:
  NODE_VERSION: '24.11.1'
  PLAYWRIGHT_VERSION: '1.57.0'

jobs:

  cache-node-modules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.1

      - name: Use Node.js
        uses: actions/setup-node@v6.1.0
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache node_modules
        uses: actions/cache@v4.3.0
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci

  format:
    needs: cache-node-modules
    runs-on: ubuntu-latest

    steps:  
      - name: Checkout code
        uses: actions/checkout@v6.0.1

      - name: Restore node_modules
        uses: actions/cache@v4.3.0
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: Use Node.js
        uses: actions/setup-node@v6.1.0
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Run format check
        run: npm run format

  lint:
    needs: cache-node-modules
    runs-on: ubuntu-latest

    steps:  
      - name: Checkout code
        uses: actions/checkout@v6.0.1

      - name: Restore node_modules
        uses: actions/cache@v4.3.0
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: Use Node.js
        uses: actions/setup-node@v6.1.0
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Run lint check
        run: npm run lint

  security:
    needs: cache-node-modules
    runs-on: ubuntu-latest

    steps:  
      - name: Checkout code
        uses: actions/checkout@v6.0.1

      - name: Restore node_modules
        uses: actions/cache@v4.3.0
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: Use Node.js
        uses: actions/setup-node@v6.1.0
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Run security check
        run: npm audit

  test:
    needs: cache-node-modules
    runs-on: ubuntu-latest

    steps:  
      - name: Checkout code
        uses: actions/checkout@v6.0.1

      - name: Restore node_modules
        uses: actions/cache@v4.3.0
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: Use Node.js
        uses: actions/setup-node@v6.1.0
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Run test
        run: npm run test:run

  test-e2e:
    timeout-minutes: 60
    needs: cache-node-modules
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.1

      - name: Restore node_modules
        uses: actions/cache@v4.3.0
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: Restore Playwright
        uses: actions/cache@v4.3.0
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}

      - name: Use Node.js
        uses: actions/setup-node@v6.1.0
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Playwright Browsers
        run: npm run test:e2e:install

      - name: Run Playwright tests
        run: npm run test:e2e:run

  typecheck:
    needs: cache-node-modules
    runs-on: ubuntu-latest

    steps:  
      - name: Checkout code
        uses: actions/checkout@v6.0.1

      - name: Restore node_modules
        uses: actions/cache@v4.3.0
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: Use Node.js
        uses: actions/setup-node@v6.1.0
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Run typecheck
        run: npm run typecheck
